name: posco-opt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - openpyxl
  - xlrd
  - pyomo
  - pytest
  - pytest-cov
  - pip
  - pip:
      - coincbc